spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?user=postgres&password=usha
    username: postgres
    password: usha
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none

server:
  port: 1234
